# Generated by Django 6.1.1 on 2026-09-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference_audio', models.FileField(upload_to='voices/')),
                ('model', models.CharField(default='chatterbox', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('model', models.CharField(default='chatterbox', max_length=50)),
                ('language', models.CharField(default='hi', max_length=20)),
                ('seed', models.IntegerField(default=12)),
                ('pace', models.FloatField(default=1.0)),
                ('output_audio', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='mytts.voice')),
            ],
        ),
    ]
